services:
  db:
    image: mysql:8.0
    container_name: back-db
    command: >
      --innodb-buffer-pool-size=128M
      --max-connections=50
      --key-buffer-size=16M
      --tmp-table-size=16M
      --max-heap-table-size=16M
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: back
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      TZ: Asia/Seoul
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5
    deploy:
      resources:
        limits:
          memory: 400M

  app:
    image: ghcr.io/prgrms-be-devcourse/nbe8-10-2-team02:latest
    container_name: back-app
    environment:
      SPRING_PROFILES_ACTIVE: prod
      DB_URL: jdbc:mysql://db:3306/back?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Seoul
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      JWT_SECRET_KEY: ${JWT_SECRET_KEY}
      IGDB_CLIENT_ID: ${IGDB_CLIENT_ID}
      IGDB_CLIENT_SECRET: ${IGDB_CLIENT_SECRET}
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy
    restart: on-failure
    deploy:
      resources:
        limits:
          memory: 512M

volumes:
  db_data:
